const INVALID_CONNECTION_TIMEOUT = 1000 * 15;
const DISTRIBUTE_INTERVAL = 1000 * 10;
const MAX_URLS_PER_VALIDATOR = 3;
const SOLANA_REWARD_AMOUNT = 100;

export {
    INVALID_CONNECTION_TIMEOUT,
    DISTRIBUTE_INTERVAL,
    MAX_URLS_PER_VALIDATOR,
    SOLANA_REWARD_AMOUNT
}